
services:
  gromacs-srcg:
    
    #command: sleep infinity

    image: docker.io/saladtechnologies/mds:001-openmm-srcg 
    container_name: "wsl-local"
    restart: "no"
    environment:
      - CLOUDFLARE_ID=${CLOUDFLARE_ID}
      - CLOUDFLARE_KEY=${CLOUDFLARE_KEY}
      - CLOUDFLARE_ENDPOINT_URL=${CLOUDFLARE_ENDPOINT_URL}
      - BUCKET=${BUCKET}
      - PREFIX=${PREFIX}
      - FOLDER=${FOLDER}
      - PDB_FILE=${PDB_FILE}
      - REPORT_FREQ=${REPORT_FREQ}
      - BENCHMARK_STEPS=${BENCHMARK_STEPS}
      - SAVING_INTERVAL_SECONDS=${SAVING_INTERVAL_SECONDS}
      - MAX_STEPS=${MAX_STEPS}
      - MAX_NO_RESPONSE_TIME=${MAX_NO_RESPONSE_TIME}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
